#src test.scx

fn main() {
  var foo = 6;

  while(true) {
    if (foo >= 5) {
      print("6 >= 5");
    }
    
    if (foo > 5) {
      print("6 > 5");
    }
    
    if (foo < 2) {
      print("6 < 2");
    }
    
    if (foo < 12) {
      print("6 < 12");
    }
    
    if (foo <= 7) {
      print("6 <= 7");
    } 
    
    if (foo <= 4) {
      print("6 <= 4");
    }
    
    if (foo >= 13) {
      print("6 >= 13");
    }
    
    if (foo >= 2) {
      print("6 >= 2");
    }
  }
}
