langums.exe --src test/test.scx --dst test_1.scx --lang test/test.l
langums.exe --src test/test.scx --dst test_2.scx --lang test/test2.l
langums.exe --src test/test.scx --dst test_3.scx --lang test/test3.l
langums.exe --src test/test.scx --dst test_4.scx --lang test/test4.l
langums.exe --src test/test.scx --dst test_5.scx --lang test/test5.l
langums.exe --src test/test.scx --dst test_6.scx --lang test/test6.l
langums.exe --src test/test.scx --dst test_7.scx --lang test/test7.l
langums.exe --src test/test.scx --dst test_8.scx --lang test/test8.l
langums.exe --src test/test.scx --dst test_9.scx --lang test/test9.l
langums.exe --src test/test.scx --dst test_10.scx --lang test/test10.l
langums.exe --src test/test.scx --dst test_11.scx --lang test/test_11.l
