mkdir test_results
langums.exe --src test/test.scx --dst test_results/test_1.scx --lang test/test.l
langums.exe --src test/test.scx --dst test_results/test_2.scx --lang test/test2.l
langums.exe --src test/test.scx --dst test_results/test_3.scx --lang test/test3.l
langums.exe --src test/test.scx --dst test_results/test_4.scx --lang test/test4.l
langums.exe --src test/test.scx --dst test_results/test_5.scx --lang test/test5.l
langums.exe --src test/test.scx --dst test_results/test_6.scx --lang test/test6.l
langums.exe --src test/test.scx --dst test_results/test_7.scx --lang test/test7.l
langums.exe --src test/test.scx --dst test_results/test_8.scx --lang test/test8.l
langums.exe --src test/test.scx --dst test_results/test_9.scx --lang test/test9.l
langums.exe --src test/test.scx --dst test_results/test_10.scx --lang test/test10.l
langums.exe --src test/test.scx --dst test_results/test_11.scx --lang test/test11.l
langums.exe --src test/test.scx --dst test_results/test_12.scx --lang test/test12.l
langums.exe --src test/test.scx --dst test_results/test_13.scx --lang test/test13.l
langums.exe --src test/test.scx --dst test_results/test_14.scx --lang test/test14.l
langums.exe --src test/test.scx --dst test_results/test_15.scx --lang test/test15.l
langums.exe --src test/test.scx --dst test_results/test_16.scx --lang test/test16.l
langums.exe --src test/test.scx --dst test_results/test_17.scx --lang test/test17.l
langums.exe --src test/test.scx --dst test_results/test_18.scx --lang test/test18.l
langums.exe --src test/test.scx --dst test_results/test_19.scx --lang test/test19.l
langums.exe --src test/test.scx --dst test_results/test_20.scx --lang test/test20.l
langums.exe --src test/test.scx --dst test_results/test_21.scx --lang test/test21.l
langums.exe --src test/test.scx --dst test_results/test_22.scx --lang test/test22.l
